use crate::{Read, Write, Error};

macro_rules! define_dynamic_type {
    ($($name:ident = $number:expr),*) => {
        #[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
        #[derive(Clone, Copy, Debug, Hash, PartialEq, Eq, PartialOrd, Ord)]
        pub enum DynamicType {
            $($name = $number),*
        }

        impl TryFrom<i32> for DynamicType {
            type Error = ();

            fn try_from(value: i32) -> Result<Self, Self::Error> {
                match value {
                    $($number => Ok(DynamicType::$name),)*
                    _ => Err(())
                }
            }
        }

        impl From<&DynamicType> for i32 {
            fn from(value: &DynamicType) -> Self {
                match value {
                    $(DynamicType::$name => $number,)*
                }
            }
        }

        impl Default for DynamicType {
            fn default() -> Self {
                Self::BoolConstant
            }
        }
    };
}

define_dynamic_type!(
    BoolConstant = 0,
    BoolVariable = 1,
    BoolNot = 2,
    BoolAnd = 3,
    BoolOr = 4,
    BoolEqualBool = 5,
    BoolEqualNumber = 6,
    BoolEqualString = 7,
    BoolEqualColor = 8,
    BoolEqualVector = 9,
    BoolEqualObject = 10,
    BoolNotEqualBool = 11,
    BoolNotEqualNumber = 12,
    BoolNotEqualString = 13,
    BoolNotEqualColor = 14,
    BoolNotEqualVector = 15,
    BoolNotEqualObject = 16,
    BoolLess = 17,
    BoolLessOrEqual = 18,
    BoolGreater = 19,
    BoolGreaterOrEqual = 20,
    BoolObjectDead = 21,
    BoolPlayerOnGround = 22,
    BoolPlayerOnWalljump = 23,
    BoolPlayerOnBooster = 24,
    BoolPlayerOnSwing = 25,
    BoolPlayerInFloatingZone = 26,
    BoolPlayerUsingGlider = 27,
    BoolObjectsColliding = 28,
    BoolInputDown = 29,
    BoolInputDownLeft = 30,
    BoolInputDownRight = 31,
    BoolInputHeld = 32,
    BoolInputHeldLeft = 33,
    BoolInputHeldRight = 34,
    BoolInputReleased = 35,
    BoolInputReleasedLeft = 36,
    BoolInputReleasedRight = 37,
    IntConstant = 38,
    IntVariable = 39,
    IntAdd = 40,
    IntSubtract = 41,
    IntMultiply = 42,
    IntDivide = 43,
    IntModulo = 44,
    IntMin = 45,
    IntMax = 46,
    IntAbs = 47,
    IntSign = 48,
    IntRound = 49,
    IntCeil = 50,
    IntFloor = 51,
    IntRandom = 52,
    IntRepeatCount = 53,
    IntObjectDirection = 54,
    IntObjectSetCount = 55,
    FloatConstant = 56,
    FloatVariable = 57,
    FloatAdd = 58,
    FloatSubtract = 59,
    FloatMultiply = 60,
    FloatDivide = 61,
    FloatModulo = 62,
    FloatMin = 63,
    FloatMax = 64,
    FloatAbs = 65,
    FloatSign = 66,
    FloatRound = 67,
    FloatCeil = 68,
    FloatFloor = 69,
    FloatCos = 70,
    FloatSin = 71,
    FloatTan = 72,
    FloatAcos = 73,
    FloatAsin = 74,
    FloatAtan = 75,
    FloatSqrt = 76,
    FloatPow = 77,
    FloatRandom = 78,
    FloatTime = 79,
    FloatSemitones = 80,
    FloatVectorX = 81,
    FloatVectorY = 82,
    FloatVectorLength = 83,
    FloatVectorLengthSqr = 84,
    FloatVectorDistance = 85,
    FloatVectorDistanceSqr = 86,
    FloatVectorDot = 87,
    FloatVectorAngle = 88,
    FloatVectorAngleBetween = 89,
    FloatObjectRotation = 90,
    FloatObjectGlobalRotation = 91,
    FloatCameraViewportSize = 92,
    FloatDamageAmount = 93,
    StringConstant = 94,
    StringVariable = 95,
    StringFromInt = 96,
    StringFromFloat = 97,
    StringConcat = 98,
    ColorConstant = 99,
    ColorValues = 100,
    ColorVariable = 101,
    ColorObjectColor = 102,
    VectorConstant = 103,
    VectorValues = 104,
    VectorVariable = 105,
    VectorAdd = 106,
    VectorSubtract = 107,
    VectorMultiply = 108,
    VectorDivide = 109,
    VectorNormalize = 110,
    VectorPerpendicular = 111,
    VectorReflect = 112,
    VectorObjectPos = 113,
    VectorObjectGlobalPos = 114,
    VectorObjectScale = 115,
    VectorObjectGlobalScale = 116,
    VectorObjectVelocity = 117,
    VectorCameraPos = 118,
    SoundConstant = 119,
    SoundVariable = 120,
    MusicConstant = 121,
    MusicVariable = 122,
    ObjectConstant = 123,
    ObjectVariable = 124,
    ObjectAnyObject = 125,
    ObjectFirstFromSet = 126,
    ObjectRandomFromSet = 127,
    ObjectElementFromSet = 128,
    ObjectSourceObject = 129,
    ObjectCollidedObject = 130,
    ObjectTargetObject = 131,
    ObjectPlayer = 132,
    ObjectParent = 133,
    ObjectSetConstant = 134,
    ObjectSetVariable = 135,
    ObjectSetConcat = 136,
    ObjectSetPlayers = 137,
    ObjectSetObjectsWithTagDeprecated = 138,
    TransitionConstant = 139,
    TransitionVariable = 140,
    EasingConstant = 141,
    EasingVariable = 142,
    ObjectSetChildren = 143,
    BoolObjectActivated = 144,
    FloatLevelTime = 145,
    BoolPlayerJumpLocked = 146,
    StringObjectTag = 147,
    SpriteConstant = 148,
    SpriteVariable = 149,
    ScriptConstant = 150,
    ScriptVariable = 151,
    BoolParameter = 152,
    IntParameter = 153,
    FloatParameter = 154,
    StringParameter = 155,
    ColorParameter = 156,
    VectorParameter = 157,
    SoundParameter = 158,
    MusicParameter = 159,
    ObjectParameter = 160,
    ObjectSetParameter = 161,
    TransitionParameter = 162,
    EasingParameter = 163,
    SpriteParameter = 164,
    ScriptParameter = 165,
    BoolObjectsCollidingWithPoint = 166,
    FloatRoundDecimals = 167,
    VectorPointerPositionDeprecated = 168,
    VectorPointerWorldPositionDeprecated = 169,
    VectorCollisionPoint = 170,
    VectorCollisionNormal = 171,
    ObjectRepeatObject = 172,
    ObjectClosestFromPoint = 173,
    ObjectSetAllObjectsDeprecated = 174,
    ObjectSetObjectsInLayer = 175,
    ObjectSetObjectsInCircle = 176,
    LayerConstant = 177,
    LayerVariable = 178,
    LayerParameter = 179,
    VectorRotate = 180,
    IntLastSoundInstance = 181,
    ObjectSetUnion = 182,
    ObjectSetIntersection = 183,
    ObjectSetDifference = 184,
    ObjectSetRemoveAtIndex = 185,
    VectorPointerPosition = 186,
    VectorPointerWorldPosition = 187,
    BoolPointerDown = 188,
    BoolPointerHeld = 189,
    BoolPointerReleased = 190,
    FloatColorR = 191,
    FloatColorG = 192,
    FloatColorB = 193,
    FloatColorA = 194,
    StringSubstring = 195,
    IntStringLength = 196,
    IntFromString = 197,
    FloatFromString = 198,
    StringFromVector = 199,
    FloatAtan2 = 200,
    PrefabConstant = 201,
    PrefabVariable = 202,
    PrefabParameter = 203,
    ObjectLastCreatedObject = 204,
    ObjectSetSetAtIndex = 205,
    ObjectSetSublist = 206,
    ObjectSetShuffle = 207,
    ObjectSetReverse = 208,
    BoolListConstant = 209,
    BoolListVariable = 210,
    BoolListParameter = 211,
    BoolListAppend = 212,
    BoolListRemove = 213,
    BoolListSetAtIndex = 214,
    BoolListRemoveAtIndex = 215,
    BoolListSublist = 216,
    BoolListSort = 217,
    BoolListShuffle = 218,
    BoolListReverse = 219,
    IntListConstant = 220,
    IntListVariable = 221,
    IntListParameter = 222,
    IntListAppend = 223,
    IntListRemove = 224,
    IntListSetAtIndex = 225,
    IntListRemoveAtIndex = 226,
    IntListSublist = 227,
    IntListSort = 228,
    IntListShuffle = 229,
    IntListReverse = 230,
    FloatListConstant = 231,
    FloatListVariable = 232,
    FloatListParameter = 233,
    FloatListAppend = 234,
    FloatListRemove = 235,
    FloatListSetAtIndex = 236,
    FloatListRemoveAtIndex = 237,
    FloatListSublist = 238,
    FloatListSort = 239,
    FloatListShuffle = 240,
    FloatListReverse = 241,
    StringListConstant = 242,
    StringListVariable = 243,
    StringListParameter = 244,
    StringListAppend = 245,
    StringListRemove = 246,
    StringListSetAtIndex = 247,
    StringListRemoveAtIndex = 248,
    StringListSublist = 249,
    StringListSort = 250,
    StringListShuffle = 251,
    StringListReverse = 252,
    ColorListConstant = 253,
    ColorListVariable = 254,
    ColorListParameter = 255,
    ColorListAppend = 256,
    ColorListRemove = 257,
    ColorListSetAtIndex = 258,
    ColorListRemoveAtIndex = 259,
    ColorListSublist = 260,
    ColorListShuffle = 261,
    ColorListReverse = 262,
    VectorListConstant = 263,
    VectorListVariable = 264,
    VectorListParameter = 265,
    VectorListAppend = 266,
    VectorListRemove = 267,
    VectorListSetAtIndex = 268,
    VectorListRemoveAtIndex = 269,
    VectorListSublist = 270,
    VectorListShuffle = 271,
    VectorListReverse = 272,
    BoolFirstFromList = 273,
    BoolRandomFromList = 274,
    BoolElementFromList = 275,
    IntFirstFromList = 276,
    IntRandomFromList = 277,
    IntElementFromList = 278,
    FloatFirstFromList = 279,
    FloatRandomFromList = 280,
    FloatElementFromList = 281,
    StringFirstFromList = 282,
    StringRandomFromList = 283,
    StringElementFromList = 284,
    ColorFirstFromList = 285,
    ColorRandomFromList = 286,
    ColorElementFromList = 287,
    VectorFirstFromList = 288,
    VectorRandomFromList = 289,
    VectorElementFromList = 290,
    BoolBoolListContains = 291,
    BoolIntListContains = 292,
    BoolFloatListContains = 293,
    BoolStringListContains = 294,
    BoolColorListContains = 295,
    BoolVectorListContains = 296,
    BoolObjectSetContains = 297,
    IntBoolListCount = 298,
    IntBoolListIndexOf = 299,
    IntIntListCount = 300,
    IntIntListIndexOf = 301,
    IntFloatListCount = 302,
    IntFloatListIndexOf = 303,
    IntStringListCount = 304,
    IntStringListIndexOf = 305,
    IntColorListCount = 306,
    IntColorListIndexOf = 307,
    IntVectorListCount = 308,
    IntVectorListIndexOf = 309,
    IntObjectSetIndexOf = 310,
    ObjectSetAllObjects = 311,
    ObjectSetAllRootObjects = 312,
    ObjectSetObjectsWithTag = 313,
    PrefabListConstant = 314,
    PrefabListVariable = 315,
    PrefabListParameter = 316,
    PrefabListAppend = 317,
    PrefabListRemove = 318,
    PrefabListSetAtIndex = 319,
    PrefabListRemoveAtIndex = 320,
    PrefabListSublist = 321,
    PrefabListShuffle = 322,
    PrefabListReverse = 323,
    PrefabFirstFromList = 324,
    PrefabRandomFromList = 325,
    PrefabElementFromList = 326,
    BoolPrefabListContains = 327,
    IntPrefabListCount = 328,
    IntPrefabIndexOf = 329,
    FloatFromInt = 330
);

impl Read for DynamicType {
    fn read(input: &mut impl std::io::Read) -> Result<Self, Error> {
        let value = i32::read(input)?;

        Self::try_from(value).map_err(|()| Error::InvalidDynamicType(value))
    }
}

impl Write for DynamicType {
    fn write(&self, output: &mut impl std::io::Write) -> Result<(), Error> {
        i32::from(self).write(output)
    }
}